#!/usr/bin/env node
// Writes bulk.js: library-shaped code the size of a Phaser game's bundle, so the engines are
// compared carrying the code a real game ships and not only the few functions that run.
//
//   node js/gen-bulk.mjs <out.js> [kilobytes]      default 1400 KB, about examples/phaser-stress's
//                                                  packed app.skpkg.js
//
// A Phaser build is mostly code a given game never calls: classes with prototype methods, event
// name tables, switch-heavy setters, closures over arrays. This generates that shape -- and,
// like a library's boot, constructs one class in twenty and calls a method on it -- so what
// differs between the engines is how they hold code: Hermes maps precompiled bytecode,
// SpiderMonkey keeps the source and parses a function when it first runs.
//
// Deterministic: the same size always gives the same file.
import { writeFileSync } from 'node:fs'

const out = process.argv[2] || 'bulk.js'
const targetBytes = Number(process.argv[3] || 1400) * 1024

let seed = 42
const random = () => {
  seed = (Math.imul(seed, 1103515245) + 12345) & 0x7fffffff
  return seed / 0x7fffffff
}
const pick = (list) => list[Math.floor(random() * list.length)]
const int = (max) => Math.floor(random() * max)
const cap = (word) => word[0].toUpperCase() + word.slice(1)

const WORDS = ('alpha scale origin bounds tint frame texture depth scroll velocity offset width height radius ' +
  'angle rotation visible active state timer delay repeat duration ease target source mask pipeline buffer ' +
  'vertex index count cursor layer tile camera zoom shake flash fade pointer button volume rate loop seek ' +
  'friction bounce gravity mass drag acceleration speed padding spacing baseline stroke fill line').split(' ')
const NAMESPACES = 'GameObjects Physics Tweens Textures Cameras Input Sound Loader Renderer Display Geom Math Scale Tilemaps'.split(' ')

const templates = [
  (c, w) => `function (a, b) {
    var s = 0, n = a | 0;
    for (var i = 0; i < n; i++) { s += Math.sqrt(i * this.${w[0]} + b) * ${int(90) + 1}; }
    return s;
  }`,
  (c, w) => `function (o) {
    var r = { ${w[0]}: o.${w[1]} || ${int(100)}, ${w[2]}: this.${w[0]} * 2, name: '${c}-${w[3]}' };
    if (r.${w[0]} > ${int(50)}) { r.${w[2]} = Math.min(r.${w[2]}, o.${w[3]} || 0); }
    return r;
  }`,
  (c, w) => `function (type, v) {
    switch (type) {
      case '${w[0]}${int(9)}': return v + this.${w[1]};
      case '${w[2]}${int(9)}': return v * ${int(20) + 1};
      case '${w[3]}': this.${w[1]} = v; return this;
      default: throw new Error('${c}: unknown ${w[0]} "' + type + '"');
    }
  }`,
  (c, w) => `function (list) {
    var self = this;
    return list.filter(function (x) { return x && x.${w[0]} !== self.${w[1]}; })
      .map(function (x, i) { return x.${w[2]} + i * ${int(10) + 1}; });
  }`,
  (c, w) => `function (x, y) {
    this.${w[0]} = x;
    this.${w[1]} = y === undefined ? x : y;
    this.dirty = true;
    return this;
  }`,
  (c, w) => `function (prefix) {
    var parts = [];
    for (var k in this) { if (typeof this[k] === 'number') parts.push(prefix + k + '=' + this[k].toFixed(2)); }
    return parts.join(';');
  }`,
  (c, w) => `function (m, x, y) {
    var a = m[0], b = m[1], c = m[2], d = m[3], det = a * d - b * c || 1;
    return { x: (x * d - y * c) / det + ${int(8)}, y: (y * a - x * b) / det - ${int(8)} };
  }`,
  (c, w) => `function (text) {
    try { var data = JSON.parse(text); this.${w[0]} = data.${w[1]}; return true; }
    catch (e) { this.lastError = '${c}.${w[2]}: ' + e.message; return false; }
  }`,
]

const parts = [
  `// Generated by js/gen-bulk.mjs -- library-shaped code, loaded before the workload. Do not edit.
(function (global) {
  'use strict';
  var registry = {}, classes = [];
`,
]
let size = parts[0].length
let n = 0
while (size < targetBytes) {
  const ns = pick(NAMESPACES)
  const name = `${cap(pick(WORDS))}${cap(pick(WORDS))}${n}`
  const fields = Array.from({ length: 4 + int(4) }, () => pick(WORDS))
  let code = `
  function ${name}(config) {
    config = config || {};
${fields.map((f, i) => `    this.${f} = config.${f} !== undefined ? config.${f} : ${int(100)};`).join('\n')}
    this.dirty = false;
  }
`
  if (n > 0 && random() < 0.4) {
    code += `  ${name}.prototype = Object.create(classes[${int(n)}].prototype);
  ${name}.prototype.constructor = ${name};
`
  }
  code += `  ${name}.prototype.init = function (a, b) { this.${fields[0]} = a; this.${fields[1]} = b; return this; };\n`
  const methods = 5 + int(6)
  for (let m = 0; m < methods; m++) {
    const words = [pick(fields), pick(fields), pick(WORDS), pick(WORDS)]
    code += `  ${name}.prototype.${pick(['get', 'set', 'update', 'apply', 'reset', 'to'])}${cap(pick(WORDS))}${m} = ${pick(templates)(name, words)};\n`
  }
  if (random() < 0.2) {
    const events = Array.from({ length: 6 + int(10) }, () => pick(WORDS))
    code += `  registry['${ns}.Events${n}'] = { ${events.map((e, i) => `${e.toUpperCase()}_${i}: '${e}${i}'`).join(', ')} };\n`
  }
  code += `  registry['${ns}.${name}'] = ${name};\n  classes.push(${name});\n`
  parts.push(code)
  size += code.length
  n++
}
parts.push(`
  // A library's boot: one class in twenty constructed and initialised.
  var touched = 0;
  for (var i = 0; i < classes.length; i += 20) touched += new classes[i]({}).init(i, i + 1).dirty ? 0 : 1;
  global.__bulk = { classes: classes.length, touched: touched, registry: registry };
})(this);
`)
writeFileSync(out, parts.join(''))
console.log(`${out}: ${n} classes, ${Math.round(size / 1024)} KB`)
